# Importing all the Necessary Libraries

In [26]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [27]:
df = pd.read_csv(r"C:\Users\aahil\OneDrive\Desktop\Flipkart\Processed_Flipkart_Data.csv")
df.head()

,Brand,Color_Group,Stars,Num_Ratings,Num_Reviews,RAM,Storage,Expandable,Processor_Brand,Display,Total_Cameras,Battery_Capacity,Price
0,SAMSUNG,Blue,4.4,126250,7344,4 GB RAM,64 GB ROM,Expandable Upto 1 TB,Exynos processor,6.60,4,6000.0,9699
1,POCO,Green,4.4,3204,151,2 GB RAM,32 GB ROM,Expandable Upto 512 GB,Mediatek processor,6.52,2,5000.0,5749
2,POCO,Blue,4.4,3204,151,2 GB RAM,32 GB ROM,Expandable Upto 512 GB,Mediatek processor,6.52,2,5000.0,5749
3,REDMI,Green,4.3,193536,12428,4 GB RAM,64 GB ROM,Expandable Upto 1 TB,Qualcomm processor,6.70,3,6000.0,9299
4,REDMI,Blue,4.3,193536,12428,4 GB RAM,64 GB ROM,Expandable Upto 1 TB,Qualcomm processor,6.70,3,6000.0,9299

In [28]:
# Checking the Datatypes of the columns
df.dtypes

Brand                object
Color_Group          object
Stars               float64
Num_Ratings           int64
Num_Reviews           int64
RAM                  object
Storage              object
Expandable           object
Processor_Brand      object
Display             float64
Total_Cameras         int64
Battery_Capacity    float64
Price                 int64
dtype: object

In [29]:
# Replacing the repeated typo errors
df.Brand.replace({"realme":"Realme","Redmi":"REDMI","Motorola":"MOTOROLA","oppo":"OPPO"
                 , "Infinix":"INFINIX","vivo":"VIVO","Google":"GOOGLE","Itel":"ITEL"
                 ,"Tecno":"TECNO","Nokia":"NOKIA"},inplace=True)

In [30]:
# Dropping the unwanted columns
df.drop(['Stars', 'Num_Ratings','Num_Reviews'],axis=1,inplace=True)

In [31]:
df.head()

,Brand,Color_Group,RAM,Storage,Expandable,Processor_Brand,Display,Total_Cameras,Battery_Capacity,Price
0,SAMSUNG,Blue,4 GB RAM,64 GB ROM,Expandable Upto 1 TB,Exynos processor,6.60,4,6000.0,9699
1,POCO,Green,2 GB RAM,32 GB ROM,Expandable Upto 512 GB,Mediatek processor,6.52,2,5000.0,5749
2,POCO,Blue,2 GB RAM,32 GB ROM,Expandable Upto 512 GB,Mediatek processor,6.52,2,5000.0,5749
3,REDMI,Green,4 GB RAM,64 GB ROM,Expandable Upto 1 TB,Qualcomm processor,6.70,3,6000.0,9299
4,REDMI,Blue,4 GB RAM,64 GB ROM,Expandable Upto 1 TB,Qualcomm processor,6.70,3,6000.0,9299

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 661 entries, 0 to 660
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Brand             661 non-null    object
 1   Color_Group       661 non-null    object
 2   RAM               661 non-null    object
 3   Storage           661 non-null    object
 4   Expandable        661 non-null    object
 5   Processor_Brand   661 non-null    object
 6   Display           661 non-null    float64
 7   Total_Cameras     661 non-null    int64
 8   Battery_Capacity  661 non-null    float64
 9   Price             661 non-null    int64
dtypes: float64(2), int64(2), object(6)
memory usage: 51.8+ KB

In [33]:
le = LabelEncoder()

for x in df.columns:
    if df[x].dtype == 'object':
        df[x] = le.fit_transform(df[x])

In [34]:
df

,Brand,Color_Group,RAM,Storage,Expandable,Processor_Brand,Display,Total_Cameras,Battery_Capacity,Price
0,16,1,3,5,0,0,6.60,4,6000.0,9699
1,13,3,1,3,4,2,6.52,2,5000.0,5749
2,13,1,1,3,4,2,6.52,2,5000.0,5749
3,14,3,3,5,0,4,6.70,3,6000.0,9299
4,14,1,3,5,0,4,6.70,3,6000.0,9299
...,...,...,...,...,...,...,...,...,...,...
656,3,1,2,1,0,2,5.45,2,3000.0,4699
657,16,1,3,0,0,2,6.50,3,5000.0,11499
658,3,3,3,5,0,6,6.70,3,5000.0,9999
659,0,6,3,4,0,2,6.70,3,5000.0,109999
660,14,3,1,3,0,2,6.52,1,5000.0,6599

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 661 entries, 0 to 660
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Brand             661 non-null    int32
 1   Color_Group       661 non-null    int32
 2   RAM               661 non-null    int32
 3   Storage           661 non-null    int32
 4   Expandable        661 non-null    int32
 5   Processor_Brand   661 non-null    int32
 6   Display           661 non-null    float64
 7   Total_Cameras     661 non-null    int64
 8   Battery_Capacity  661 non-null    float64
 9   Price             661 non-null    int64
dtypes: float64(2), int32(6), int64(2)
memory usage: 36.3 KB

In [11]:
df.shape

(661, 10)

In [12]:
X = df.drop(columns=['Price'])
y = df['Price']

In [13]:
# Splitting the data using train-test split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(X, y, test_size=0.10, random_state=10)

In [25]:
from sklearn.metrics import *
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

# List of models to run
models = [
    ("Logistic Regression", LogisticRegression()),
    ("Random Forest", RandomForestClassifier()),
    ("Support Vector Machine", SVC()),
    ("K-Nearest Neighbors", KNeighborsClassifier()),
    ("Naive Bayes", GaussianNB())
]

# Loop through the models and evaluate each one
for name, model in models:
    # Fit the model
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    
    # Calculate metrics
    accuracy = accuracy_score(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    mape = mean_absolute_percentage_error(y_test, y_pred)
    
    # Print the model name and metrics
    print(f"{name}:")
    print(f"  Accuracy: {accuracy:.4f}")
    print(f"  R² Score: {r2:.4f}")
    print(f"  Mean Absolute Error (MAE): {mae:.4f}")
    print(f"  Mean Absolute Percentage Error (MAPE): {mape:.4f}")
    print()

Logistic Regression:
  Accuracy: 0.0448
  R² Score: 0.2899
  Mean Absolute Error (MAE): 6569.6866
  Mean Absolute Percentage Error (MAPE): 0.4047

Random Forest:
  Accuracy: 0.4627
  R² Score: 0.9823
  Mean Absolute Error (MAE): 914.4030
  Mean Absolute Percentage Error (MAPE): 0.0549

Support Vector Machine:
  Accuracy: 0.0299
  R² Score: -0.3844
  Mean Absolute Error (MAE): 10210.6418
  Mean Absolute Percentage Error (MAPE): 0.3988

K-Nearest Neighbors:
  Accuracy: 0.1343
  R² Score: 0.6994
  Mean Absolute Error (MAE): 4289.9701
  Mean Absolute Percentage Error (MAPE): 0.2124

Naive Bayes:
  Accuracy: 0.1940
  R² Score: 0.8438
  Mean Absolute Error (MAE): 3276.8358
  Mean Absolute Percentage Error (MAPE): 0.1853

# Training and evaluating different Machine Learning models

In [14]:
pip install pycaret

Requirement already satisfied: pycaret in c:\users\aahil\anaconda3\lib\site-packages (3.3.2)
Requirement already satisfied: ipython>=5.5.0 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (8.15.0)
Requirement already satisfied: ipywidgets>=7.6.5 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (8.0.4)
Requirement already satisfied: tqdm>=4.62.0 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (4.65.0)
Requirement already satisfied: numpy<1.27,>=1.21 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (1.24.3)
Requirement already satisfied: pandas<2.2.0 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (2.1.4)
Requirement already satisfied: jinja2>=3 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (3.1.2)
Requirement already satisfied: scipy<=1.11.4,>=1.6.1 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (1.11.1)
Requirement already satisfied: joblib<1.4,>=1.2.0 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (1.2.0)
Requirement already satisfied: scikit-learn>1.4.0 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (1.4.2)
Requirement already satisfied: pyod>=1.1.3 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (2.0.1)
Requirement already satisfied: imbalanced-learn>=0.12.0 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (0.12.3)
Requirement already satisfied: category-encoders>=2.4.0 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (2.6.3)
Requirement already satisfied: lightgbm>=3.0.0 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (4.4.0)
Requirement already satisfied: numba>=0.55.0 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (0.57.1)
Requirement already satisfied: requests>=2.27.1 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (2.31.0)
Requirement already satisfied: psutil>=5.9.0 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (5.9.0)
Requirement already satisfied: markupsafe>=2.0.1 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (2.1.1)
Requirement already satisfied: importlib-metadata>=4.12.0 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (6.0.0)
Requirement already satisfied: nbformat>=4.2.0 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (5.9.2)
Requirement already satisfied: cloudpickle in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (2.2.1)
Requirement already satisfied: deprecation>=2.1.0 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (2.1.0)
Requirement already satisfied: xxhash in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (2.0.2)
Requirement already satisfied: matplotlib<3.8.0 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (3.7.2)
Requirement already satisfied: scikit-plot>=0.3.7 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (0.3.7)
Requirement already satisfied: yellowbrick>=1.4 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (1.5)
Requirement already satisfied: plotly>=5.14.0 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (5.22.0)
Requirement already satisfied: kaleido>=0.2.1 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (0.2.1)
Requirement already satisfied: schemdraw==0.15 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (0.15)
Requirement already satisfied: plotly-resampler>=0.8.3.1 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (0.10.0)
Requirement already satisfied: statsmodels>=0.12.1 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (0.14.0)
Requirement already satisfied: sktime==0.26.0 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (0.26.0)
Requirement already satisfied: tbats>=1.1.3 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (1.1.3)
Requirement already satisfied: pmdarima>=2.0.4 in c:\users\aahil\anaconda3\lib\site-packages (from pycaret) (2.0.4)
Requirement already satisfied: packaging in c:\users\aahil\anaconda3\lib\site-packages (from sktime==0.26.0->pycaret) (23.1)
Requirement already satisfied: scikit-base<0.8.0 in c:\users\aahil\anaconda3\lib\site-packages (from sktime==0.26.0->pycaret) (0.7.8)
Requirement already satisfied: patsy>=0.5.1 in c:\users\aahil\anaconda3\lib\site-packages (from category-encoders>=2.4.0->pycaret) (0.5.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\aahil\anaconda3\lib\site-packages (from imbalanced-learn>=0.12.0->pycaret) (3.5.0)
Requirement already satisfied: zipp>=0.5 in c:\users\aahil\anaconda3\lib\site-packages (from importlib-metadata>=4.12.0->pycaret) (3.11.0)
Requirement already satisfied: backcall in c:\users\aahil\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (0.2.0)
Requirement already satisfied: decorator in c:\users\aahil\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\aahil\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (0.18.1)
Requirement already satisfied: matplotlib-inline in c:\users\aahil\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (0.1.6)
Requirement already satisfied: pickleshare in c:\users\aahil\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in c:\users\aahil\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (3.0.36)
Requirement already satisfied: pygments>=2.4.0 in c:\users\aahil\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (2.15.1)
Requirement already satisfied: stack-data in c:\users\aahil\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (0.2.0)
Requirement already satisfied: traitlets>=5 in c:\users\aahil\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (5.7.1)
Requirement already satisfied: colorama in c:\users\aahil\anaconda3\lib\site-packages (from ipython>=5.5.0->pycaret) (0.4.6)
Requirement already satisfied: ipykernel>=4.5.1 in c:\users\aahil\anaconda3\lib\site-packages (from ipywidgets>=7.6.5->pycaret) (6.25.0)
Requirement already satisfied: widgetsnbextension~=4.0 in c:\users\aahil\anaconda3\lib\site-packages (from ipywidgets>=7.6.5->pycaret) (4.0.5)
Requirement already satisfied: jupyterlab-widgets~=3.0 in c:\users\aahil\anaconda3\lib\site-packages (from ipywidgets>=7.6.5->pycaret) (3.0.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\aahil\anaconda3\lib\site-packages (from matplotlib<3.8.0->pycaret) (1.0.5)
Requirement already satisfied: cycler>=0.10 in c:\users\aahil\anaconda3\lib\site-packages (from matplotlib<3.8.0->pycaret) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\aahil\anaconda3\lib\site-packages (from matplotlib<3.8.0->pycaret) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\aahil\anaconda3\lib\site-packages (from matplotlib<3.8.0->pycaret) (1.4.4)
Requirement already satisfied: pillow>=6.2.0 in c:\users\aahil\anaconda3\lib\site-packages (from matplotlib<3.8.0->pycaret) (9.4.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in c:\users\aahil\anaconda3\lib\site-packages (from matplotlib<3.8.0->pycaret) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\aahil\anaconda3\lib\site-packages (from matplotlib<3.8.0->pycaret) (2.8.2)
Requirement already satisfied: fastjsonschema in c:\users\aahil\anaconda3\lib\site-packages (from nbformat>=4.2.0->pycaret) (2.16.2)
Requirement already satisfied: jsonschema>=2.6 in c:\users\aahil\anaconda3\lib\site-packages (from nbformat>=4.2.0->pycaret) (4.17.3)
Requirement already satisfied: jupyter-core in c:\users\aahil\anaconda3\lib\site-packages (from nbformat>=4.2.0->pycaret) (5.3.0)
Requirement already satisfied: llvmlite<0.41,>=0.40.0dev0 in c:\users\aahil\anaconda3\lib\site-packages (from numba>=0.55.0->pycaret) (0.40.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\aahil\anaconda3\lib\site-packages (from pandas<2.2.0->pycaret) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\aahil\anaconda3\lib\site-packages (from pandas<2.2.0->pycaret) (2023.3)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\aahil\anaconda3\lib\site-packages (from plotly>=5.14.0->pycaret) (8.2.2)
Requirement already satisfied: dash>=2.9.0 in c:\users\aahil\anaconda3\lib\site-packages (from plotly-resampler>=0.8.3.1->pycaret) (2.17.1)
Requirement already satisfied: orjson<4.0.0,>=3.8.0 in c:\users\aahil\anaconda3\lib\site-packages (from plotly-resampler>=0.8.3.1->pycaret) (3.10.6)
Requirement already satisfied: tsdownsample>=0.1.3 in c:\users\aahil\anaconda3\lib\site-packages (from plotly-resampler>=0.8.3.1->pycaret) (0.1.3)
Requirement already satisfied: Cython!=0.29.18,!=0.29.31,>=0.29 in c:\users\aahil\anaconda3\lib\site-packages (from pmdarima>=2.0.4->pycaret) (3.0.10)
Requirement already satisfied: urllib3 in c:\users\aahil\anaconda3\lib\site-packages (from pmdarima>=2.0.4->pycaret) (1.26.16)
Requirement already satisfied: setuptools!=50.0.0,>=38.6.0 in c:\users\aahil\anaconda3\lib\site-packages (from pmdarima>=2.0.4->pycaret) (68.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\aahil\anaconda3\lib\site-packages (from requests>=2.27.1->pycaret) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\aahil\anaconda3\lib\site-packages (from requests>=2.27.1->pycaret) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\aahil\anaconda3\lib\site-packages (from requests>=2.27.1->pycaret) (2024.2.2)
Requirement already satisfied: Flask<3.1,>=1.0.4 in c:\users\aahil\anaconda3\lib\site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (2.2.2)
Requirement already satisfied: Werkzeug<3.1 in c:\users\aahil\anaconda3\lib\site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (2.2.3)
Requirement already satisfied: dash-html-components==2.0.0 in c:\users\aahil\anaconda3\lib\site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (2.0.0)
Requirement already satisfied: dash-core-components==2.0.0 in c:\users\aahil\anaconda3\lib\site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (2.0.0)
Requirement already satisfied: dash-table==5.0.0 in c:\users\aahil\anaconda3\lib\site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (5.0.0)
Requirement already satisfied: typing-extensions>=4.1.1 in c:\users\aahil\anaconda3\lib\site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (4.7.1)
Requirement already satisfied: retrying in c:\users\aahil\anaconda3\lib\site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (1.3.4)
Requirement already satisfied: nest-asyncio in c:\users\aahil\anaconda3\lib\site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (1.5.6)
Requirement already satisfied: comm>=0.1.1 in c:\users\aahil\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (0.1.2)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\aahil\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (1.6.7)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\users\aahil\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (7.4.9)
Requirement already satisfied: pyzmq>=20 in c:\users\aahil\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (23.2.0)
Requirement already satisfied: tornado>=6.1 in c:\users\aahil\anaconda3\lib\site-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (6.3.2)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\aahil\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=5.5.0->pycaret) (0.8.3)
Requirement already satisfied: attrs>=17.4.0 in c:\users\aahil\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (22.1.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in c:\users\aahil\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (0.18.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\aahil\anaconda3\lib\site-packages (from jupyter-core->nbformat>=4.2.0->pycaret) (3.10.0)
Requirement already satisfied: pywin32>=300 in c:\users\aahil\anaconda3\lib\site-packages (from jupyter-core->nbformat>=4.2.0->pycaret) (305.1)
Requirement already satisfied: six in c:\users\aahil\anaconda3\lib\site-packages (from patsy>=0.5.1->category-encoders>=2.4.0->pycaret) (1.16.0)
Requirement already satisfied: wcwidth in c:\users\aahil\anaconda3\lib\site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython>=5.5.0->pycaret) (0.2.5)
Requirement already satisfied: executing in c:\users\aahil\anaconda3\lib\site-packages (from stack-data->ipython>=5.5.0->pycaret) (0.8.3)
Requirement already satisfied: asttokens in c:\users\aahil\anaconda3\lib\site-packages (from stack-data->ipython>=5.5.0->pycaret) (2.0.5)
Requirement already satisfied: pure-eval in c:\users\aahil\anaconda3\lib\site-packages (from stack-data->ipython>=5.5.0->pycaret) (0.2.2)
Requirement already satisfied: itsdangerous>=2.0 in c:\users\aahil\anaconda3\lib\site-packages (from Flask<3.1,>=1.0.4->dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (2.0.1)
Requirement already satisfied: click>=8.0 in c:\users\aahil\anaconda3\lib\site-packages (from Flask<3.1,>=1.0.4->dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (8.0.4)
Requirement already satisfied: entrypoints in c:\users\aahil\anaconda3\lib\site-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets>=7.6.5->pycaret) (0.4)
Note: you may need to restart the kernel to use updated packages.

In [18]:
import pandas as pd
from pycaret.classification import *
from pycaret.regression import *

# Load your dataset
data=pd.read_csv(r"C:\Users\aahil\OneDrive\Desktop\Flipkart\Processed_Flipkart_Data.csv")
data.head()

,Brand,Color_Group,Stars,Num_Ratings,Num_Reviews,RAM,Storage,Expandable,Processor_Brand,Display,Total_Cameras,Battery_Capacity,Price
0,SAMSUNG,Blue,4.4,126250,7344,4 GB RAM,64 GB ROM,Expandable Upto 1 TB,Exynos processor,6.60,4,6000.0,9699
1,POCO,Green,4.4,3204,151,2 GB RAM,32 GB ROM,Expandable Upto 512 GB,Mediatek processor,6.52,2,5000.0,5749
2,POCO,Blue,4.4,3204,151,2 GB RAM,32 GB ROM,Expandable Upto 512 GB,Mediatek processor,6.52,2,5000.0,5749
3,REDMI,Green,4.3,193536,12428,4 GB RAM,64 GB ROM,Expandable Upto 1 TB,Qualcomm processor,6.70,3,6000.0,9299
4,REDMI,Blue,4.3,193536,12428,4 GB RAM,64 GB ROM,Expandable Upto 1 TB,Qualcomm processor,6.70,3,6000.0,9299

In [19]:
# Setting up the PyCaret environment
clf_setup = setup(data, target='Price')

In [20]:
# Compare different models
best_model = compare_models()

In [21]:
et = create_model('et')

In [22]:
# Tune hyperparameters of the model
tuned_dt= tune_model(et)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).